### ISSUE TITLE
Switch.rb

### ISSUE THREAD

**Issue by kelseyleftwich** [byrgenwerth-freshman/DControl#2]
Add more attributes based on Switchmap data.

**Comment by byrgenwerth-freshman** [comment]
In the doc/REPEATED_COMMANDS file, there is the command for how to add the switch scaffolding. So first destroy the scaffolding and then add it again with the added attributes.

**Comment by byrgenwerth-freshman** [comment]
Temporary List of Needed Fields
- Model
- Cisco Product Name
- Cisco Product Comment
- sysDecr
- sysName
- sysUptime //Not sure if this is needed

Then I think we will need a module table and a port table. Any thoughts?

**Comment by byrgenwerth-freshman** [comment]
For module table
- Model
- Description
- Serial Number
- HW
- SW
- FW
- Module ID
- Associate Switch

For Port Tabel
- Port
- VLAN
- State
- Days Inactive
- Duplex
- Port Label
- What (Via CPD)
- MAC Address
- NIC manufacturer
- IP Address
- DNS Name
- Associated Module

**Comment by byrgenwerth-freshman** [comment]
Do we need to make this time dependent?

**Comment by ShuaiZhao** [comment]
We might need the location for each switches. My thought is listing everything we might use in the future and category them along with experiments.

Jack

**Comment by byrgenwerth-freshman** [comment]
So I typed up the new tables below. Vote aye for yes! Vote naye for no! Please give a reason for no. If everything is good then I will implement it today or tomorrow.

For Switches
-    Model
-    Cisco Product Name
-    Cisco Product Comment
-    sysDecr
-    sysName
-    sysUptime
-    id
-    Location //Building Name
-    Time Collected

For module table
-    Model
-    Description
-    Serial Number
-    HW
-    SW
-    FW
-    Module ID
-    Switch ID
-    ID
-    Time Collected
  For Port Tabel
-    Port
-    VLAN
-    State
-    Days Inactive
-    Duplex
-    Port Label
-    What (Via CPD)
-    MAC Address
-    NIC manufacturer
-    IP Address
-    DNS Name
-    Module ID
-    ID
-    Time Collected

**Comment by kelseyleftwich** [comment]
Your router table is for routers and switches, correct?

On Wed, May 29, 2013 at 12:29 PM, Matt notifications@github.com wrote:

> So I typed up the new tables below. Vote aye for yes! Vote naye for no!
> Please give a reason for no. If everything is good then I will implement it
> today or tomorrow.
> 
> For routers
> - Model
> - Cisco Product Name
> - Cisco Product Comment
> - sysDecr
> - sysName
> - sysUptime
> - id
> - Location //Building Name
> - Time Collected
> 
> For module table
> - Model
> - Description
> - Serial Number
> - HW
> - SW
> - FW
> - Module ID
> - Switch ID
> - ## ID
>   
>   Time Collected
>   
>   ## For Port Tabel
>   
>   ## Port
>   
>   ## VLAN
>   
>   ## State
>   
>   ## Days Inactive
>   
>   ## Duplex
>   
>   ## Port Label
>   
>   ## What (Via CPD)
>   
>   ## MAC Address
>   
>   ## NIC manufacturer
>   
>   ## IP Address
>   
>   ## DNS Name
>   
>   ## Module ID
>   
>   ## ID
>   
>   Time Collected
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/matao/DControl/issues/2#issuecomment-18632697
> .

## 

Kelsey Leftwich

**Comment by byrgenwerth-freshman** [comment]
Yes that should say switch. I will edit it.

**Comment by ShuaiZhao** [comment]
looks good to me.

**Comment by byrgenwerth-freshman** [comment]
I just updated the db based on the above information. This is closed.

**Comment by ShuaiZhao** [comment]
what is the db name you are using in postgresql?

**Comment by byrgenwerth-freshman** [comment]
They aren't in postgreql yet. It is still using sqlite. I'll put this info in the issue you started.

**Comment by ShuaiZhao** [comment]
Got you.
